name: Build Quarkus GraalVM Native Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'      # See 'Options' section below for all supported versions
        distribution: 'graalvm' # See 'Options' section below for all available distributions
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Installation check
      run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

    - name: Build Quarkus Application
      run: ./mvnw clean package -Pnative

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: native-executable
        path: target/*-runner

    - name: Deploy files by SSH
      uses: appleboy/scp-action@v0.1.4
      with:
         host: ${{ secrets.SSH_SERVER }}
         username: ${{ secrets.SSH_LOGIN }}
         password: ${{ secrets.SSH_PASSWORD }}
         port: ${{ secrets.SSH_PORT }}
         source: target/*-runner
         target: /home/infrastructure_test
